apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment

spec:
  replicas: 1
  selector:
   matchLabels:
     app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: streamlit
        image: manokac55/movie-recommendation-system
        ports:
          - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: my-app
  ports:
  - port: 8501
    targetPort: 8501
  type: LoadBalancer
